### ISSUE TITLE
Fields in descriptor don't match properties on features

### ISSUE THREAD

**Issue by danfowler** [datasets/geo-countries#3]
This is an excellent resource! 🌐 

The `datapackage.json` raises a couple of questions for me, though.  It lists a `schema` on the GeoJSON resource with the following properties: "name" and "ISO3166-1-Alpha-3".  

The first question is should a Geo Data Package have a Tabular Data Package schema?  If it does, should it not be aligned with the `properties` found on each feature: "ADMIN" and "ISO_A3"?

**Comment by lexman** [comment]
Hello Daniel, you're right : NE move the names of thier fields to uppercase, so replacement didn't work anymore. I've fixed back the names of the fields.

As for should a Geo Data Package have a schema ? I think I was inspired by this doc : http://dataprotocols.org/json-table-schema . But now that I read it again, I understund GeoJson isn't a specil case for tabular json, so the spec does not apply. But, the concept is very similar, so there definitly be a spec ! 

Also I do'nt think it's wrong to specify a schema, nothing specifies how I should be interpreted.

What do you think ?

**Comment by danfowler** [comment]
@lexman I think you're right.  It's worth specifying a schema and it's worth pulling from previous work on JSON Table Schema.  Re-reading the Data Packages spec, I see the following:

> NOTE: the Data Package specification places no restrictions on the form of this Object. This flexibility enables specific communities to define schemas appropriate for the data they manage. As an example, the Tabular Data Package specification requires the schema value to conform to JSON Table Schema.

It's probably worth booting a [new issue](https://github.com/dataprotocols/dataprotocols/issues) for what a GeoJSON Data Package schema should look like.  I guess to answer that, we need to answer what "good" geodata looks like.

http://dataprotocols.org/data-packages/#resource-schemas

**Comment by lexman** [comment]
Is it coverd by this issue : https://github.com/dataprotocols/dataprotocols/issues/86 ?

I'm sorry, though,  I don't have the energy right now to start a spec. I really need to finish a lot af things before I'd dive into something demanding like an RFC.

**Comment by danfowler** [comment]
@lexman yes, you're right :).

**Comment by lexman** [comment]
So I close the issue because the name of the colums are back, and there is already an issue requesting spec for geojson...
