### ISSUE TITLE
Missing ISO_A3 codes

### ISSUE THREAD

**Issue by datadiver0x0** [datasets/geo-countries#5]
Hi, I found that the following ISO_A3 codes are listed as "-99".

Norway, NOR
France, FRA

Thanks for dataset,
dd0x0

**Comment by jbaker-dstl** [comment]
I came here to report the same thing - would like to see this fixed as the dataset is otherwise very useful.

**Comment by bdeining** [comment]
https://github.com/datasets/geo-countries/pull/6

**Comment by Mikanebu** [comment]
FIXED
